[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storage-io.workspace = true
gstd.workspace = true
hashbrown.workspace = true
primitive-types.workspace = true


[build-dependencies]
gear-wasm-builder.workspace = true
gmeta.workspace = true
storage-io.workspace = true