name: sunrise
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_easyloading: ^3.0.5
  isar: ^3.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_xupdate: ^3.0.0
  easy_refresh: ^3.3.2+1
  flutter_inappwebview: ^5.7.2+3
  flutter_easy_permission: ^1.1.2
  flutter_animate: ^4.1.1+1
  smooth_page_indicator: ^1.1.0
  web3dart: ^2.6.1
  dart_bip32_bip44: ^0.2.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  crypto: ^3.0.3
  device_info_plus: ^9.0.2
  encrypt: ^5.0.1
  http: ^0.13.6
  dart_ping: ^8.0.1
  dart_ping_ios: ^3.0.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  isar_flutter_libs: ^3.1.0+1
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  flutter_cache_manager: ^3.3.0
  local_auth: ^2.1.6
  xmtp: ^1.0.0
  intl: ^0.18.1
  flutter_isolate: ^2.0.4

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter: 
  uses-material-design: true
# 引入图片
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/
    - assets/javascript/

