[package]
name = "vault-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec.workspace = true
gstd.workspace = true
scale-info.workspace = true
primitive-types.workspace = true
hashbrown.workspace = true
gmeta.workspace = true
storage-io.workspace = true
entry-io.workspace = true
